name: Docker Series Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker build golang
        run: |
          docker build ./golang -t jemalmtahir/docker-gs-ping:1.0.0
      - name: docker push
        run: |
          docker push jemalmtahir/docker-gs-ping:1.0.0
